services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - app-network

    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_USER=pos_user
      - DB_NAME=pos
      - DB_PASS=(098JhhGFUI%%
      - DB_HOST=mysql
      - DIALECT=mysql
      - PORT=4000
      - TASK_INTERVAL=30000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=(098JhhGFUI%%
      - MYSQL_DATABASE=pos
      - MYSQL_USER=pos_user
      - MYSQL_PASSWORD=(098JhhGFUI%%
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p(098JhhGFUI%%" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
